from typing import Any, Awaitable, Optional, Sequence

def version() -> str: ...

class NativeProducer:
    def __init__(
        self,
        redis_url: str,
        queue_name: str,
        *,
        pool_size: Optional[int] = ...,
        max_stream_len: Optional[int] = ...,
        max_delay_secs: Optional[int] = ...,
    ) -> None: ...
    def stream_key(self) -> str: ...
    def delayed_key(self) -> str: ...
    def dlq_key(self) -> str: ...
    def producer_id(self) -> str: ...
    def add(self, payload: bytes) -> Awaitable[str]: ...
    def add_with_options(
        self, payload: bytes, opts: dict[str, Any]
    ) -> Awaitable[str]: ...
    def add_in(self, delay_ms: int, payload: bytes) -> Awaitable[str]: ...
    def add_in_with_options(
        self, delay_ms: int, payload: bytes, opts: dict[str, Any]
    ) -> Awaitable[str]: ...
    def add_at(self, when_ms: int, payload: bytes) -> Awaitable[str]: ...
    def add_at_with_options(
        self, when_ms: int, payload: bytes, opts: dict[str, Any]
    ) -> Awaitable[str]: ...
    def add_bulk(self, payloads: Sequence[bytes]) -> Awaitable[list[str]]: ...
    def add_bulk_with_options(
        self, payloads: Sequence[bytes], opts: dict[str, Any]
    ) -> Awaitable[list[str]]: ...
    def add_in_bulk(
        self, delay_ms: int, payloads: Sequence[bytes]
    ) -> Awaitable[list[str]]: ...
    def cancel_delayed(self, job_id: str) -> Awaitable[bool]: ...
    def cancel_delayed_bulk(
        self, job_ids: Sequence[str]
    ) -> Awaitable[list[bool]]: ...
    def peek_dlq(self, limit: int) -> Awaitable[list[dict[str, Any]]]: ...
    def replay_dlq(self, limit: int) -> Awaitable[int]: ...
    def upsert_repeatable(self, spec: dict[str, Any]) -> Awaitable[str]: ...
    def list_repeatable(
        self, limit: int
    ) -> Awaitable[list[dict[str, Any]]]: ...
    def remove_repeatable_by_key(self, key: str) -> Awaitable[bool]: ...
