from typing import Any, Awaitable, Callable, Optional, Sequence

def version() -> str: ...

class NativeJob:
    @property
    def id(self) -> str: ...
    @property
    def payload(self) -> bytes: ...
    @property
    def created_at_ms(self) -> int: ...
    @property
    def attempt(self) -> int: ...

class NativeProducer:
    def __init__(
        self,
        redis_url: str,
        queue_name: str,
        *,
        pool_size: Optional[int] = ...,
        max_stream_len: Optional[int] = ...,
        max_delay_secs: Optional[int] = ...,
    ) -> None: ...
    def stream_key(self) -> str: ...
    def delayed_key(self) -> str: ...
    def dlq_key(self) -> str: ...
    def producer_id(self) -> str: ...
    def add(self, payload: bytes) -> Awaitable[str]: ...
    def add_with_options(
        self, payload: bytes, opts: dict[str, Any]
    ) -> Awaitable[str]: ...
    def add_in(self, delay_ms: int, payload: bytes) -> Awaitable[str]: ...
    def add_in_with_options(
        self, delay_ms: int, payload: bytes, opts: dict[str, Any]
    ) -> Awaitable[str]: ...
    def add_at(self, when_ms: int, payload: bytes) -> Awaitable[str]: ...
    def add_at_with_options(
        self, when_ms: int, payload: bytes, opts: dict[str, Any]
    ) -> Awaitable[str]: ...
    def add_bulk(self, payloads: Sequence[bytes]) -> Awaitable[list[str]]: ...
    def add_bulk_with_options(
        self, payloads: Sequence[bytes], opts: dict[str, Any]
    ) -> Awaitable[list[str]]: ...
    def add_in_bulk(
        self, delay_ms: int, payloads: Sequence[bytes]
    ) -> Awaitable[list[str]]: ...
    def cancel_delayed(self, job_id: str) -> Awaitable[bool]: ...
    def cancel_delayed_bulk(
        self, job_ids: Sequence[str]
    ) -> Awaitable[list[bool]]: ...
    def peek_dlq(self, limit: int) -> Awaitable[list[dict[str, Any]]]: ...
    def replay_dlq(self, limit: int) -> Awaitable[int]: ...
    def upsert_repeatable(self, spec: dict[str, Any]) -> Awaitable[str]: ...
    def list_repeatable(
        self, limit: int
    ) -> Awaitable[list[dict[str, Any]]]: ...
    def remove_repeatable_by_key(self, key: str) -> Awaitable[bool]: ...

class NativeConsumer:
    def __init__(
        self,
        redis_url: str,
        queue_name: str,
        *,
        concurrency: int = 1,
        max_attempts: int = 25,
        group: str = "default",
        consumer_id: Optional[str] = None,
        read_block_ms: Optional[int] = None,
        read_count: Optional[int] = None,
        claim_min_idle_ms: Optional[int] = None,
        max_payload_bytes: Optional[int] = None,
        dlq_max_stream_len: Optional[int] = None,
        events_enabled: bool = True,
        delayed_enabled: bool = True,
    ) -> None: ...
    def run(
        self, handler: Callable[[NativeJob], Awaitable[Any]]
    ) -> Awaitable[None]: ...
    def shutdown(self) -> None: ...

class NativeScheduler:
    def __init__(
        self,
        redis_url: str,
        queue_name: str,
        *,
        tick_interval_ms: Optional[int] = None,
        batch: Optional[int] = None,
        max_stream_len: Optional[int] = None,
        lock_ttl_secs: Optional[int] = None,
        holder_id: Optional[str] = None,
    ) -> None: ...
    def run(self) -> Awaitable[None]: ...
    def shutdown(self) -> None: ...
